<?php


/*
 *	These are the default configuration settings of this hotglue 
 *	installation. Do not edit this file directly but overwrite specific 
 *	variables by setting them in the user-config.inc.php file, which 
 *	will not be overwritten by future updates.
 */


error_reporting(E_ALL);						// see php documentation

// try to include user configuration
@include('user-config.inc.php');

// otherwise fall back to these defaults
@define('ALWAYS_PROMPT_CREATE_PAGE', false);	// invoke the "create page" controller when trying to access a non-existing page even if the user is not logged in yet (otherwise they receive a 404)
@define('AUTH_METHOD', 'basic');			// can be digest, basic, db or none

// DB_AUTH_* only apply when AUTH_METHOD is 'db' - authenticates against a
// UserCake-compatible accounts table (columns Username_Clean, Password,
// Active) instead of the fixed AUTH_USER/AUTH_PASSWORD pair above; the
// authenticated account must still match this site's own AUTH_USER, since
// one database can back many hotglue sites each with a single owner
@define('DB_AUTH_HOST', '');				// MySQL host (leave empty to disable 'db' auth)
@define('DB_AUTH_USER', '');				// MySQL username
@define('DB_AUTH_PASSWORD', '');			// MySQL password
@define('DB_AUTH_NAME', '');				// MySQL database name
@define('DB_AUTH_TABLE', 'userCake_Users');	// table holding user accounts

// DON'T set username and password here!
// instead rename file user-config.inc.php-dist to user-config.inc.php
// and set you credentials there
@define('AUTH_USER', 'admin');
@define('AUTH_PASSWORD', 'changeme');

@define('BASE_URL', '');					// auto-detected if empty (don't use BASE_URL in custom code but rather base_url() below)
@define('CACHE_TIME', 0);				// cache time in seconds (zero to disable)
//@define('CACHE_TIME', 60*60);				// cache time in seconds (zero to disable)
@define('CONTENT_DIR', 'content');			// content directory, must be writable
@define('DEFAULT_PAGE', 'start');
@define('DEFAULT_TO_EDIT', false);			// edit pages by default
@define('FAVICON', 'img/favicon.ico');		// can be empty or an absolute url
@define('HOTGLUE_VERSION', '1.9.0');		// expected api.version.patchlevel
@define('LOCK_TIME', 5000);					// maximum time in ms to wait for an object lock
@define('LOG_FILE', 'content/log.txt');		// log file, must be writable
@define('LOG_LEVEL', 'error');				// minimum log level (can be error, warn, info, debug)
@define('SHORT_URLS', false);				// use short urls internally
@define('SHOW_FRONTEND_ERRORS', true);
@define('SITE_NAME', 'hotglue 1.9');
@define('USE_HOTGLUE_ERRORS', true);		// use hotglue theming for error pages
@define('USE_MIN_FILES', true);				// use minified files if possible
// default modules
@define('IMAGE_JPEG_QUAL', 90);				// quality for jpeg resizing (0 < 100)
@define('IMAGE_PNG_QUAL', 7);				// quality for png resizing (9 < 0)
@define('IMAGE_WEBP_QUAL', 90);				// quality for webp resizing (0 < 100)
@define('IMAGE_RESIZING', true);			// resize uploaded images on the server (needs gd installed)
@define('IMAGE_RESIZE_MAX_DPR', 2);			// cap on window.devicePixelRatio when requesting a server-side resize, so images stay sharp on HiDPI/Retina displays instead of being upscaled by the browser (1 disables this, higher values trade file size for extra sharpness on very-high-DPR devices)
@define('IMAGE_UPLOAD_RESIZE_LARGER', '120%');	// automatically resize uploaded image when larger than n% of window width or height (set to 0% to disable)
@define('IMAGE_UPLOAD_RESIZE_TO', '80%');		// target size in n% of window width or height
@define('IMAGE_UPLOAD_MAX_WIDTH', 512);		// cap the on-canvas size of a newly-uploaded image to at most this many pixels wide (0 to disable) - the original file/resolution is untouched, "reset image size" still shows it at full size
@define('IMAGE_UPLOAD_MAX_HEIGHT', 512);		// same as above, for height
@define('OBJECT_DEFAULT_COLORS', '#61b9cf #ff00ff #ffff00');		// default colors for new objects (space-separated string)
@define('RESERVED_PAGE_NAMES', 'code edit pages favicon');	// page names used internaly and thus unavailable
// centered layout mode: the content container's width, and the bounds the
// editor's drag handles may set it to. Only used by pages that opt in to
// page-layout-mode 'centered'; every page defaults to 'infinite', which is
// hotglue's original unbounded canvas.
@define('PAGE_DEFAULT_CONTAINER_WIDTH', 960);	// default centered container width in px
@define('PAGE_MIN_CONTAINER_WIDTH', 320);		// narrowest the handles may drag to
@define('PAGE_MAX_CONTAINER_WIDTH', 4000);		// widest the handles may drag to
@define('PAGE_DEFAULT_GRID_X', 50);			// default grid x spacing in px
@define('PAGE_DEFAULT_GRID_Y', 50);			// default grid y spacing in px
@define('PAGE_GUIDES_X', '');				// show a grid line after n horizontal px (space-separated string)
@define('PAGE_GUIDES_Y', '');				// show a grid line after n vertical px (space-separated string)
@define('PAGES_NEED_AUTH', true);			// page browser needs authentication
@define('TEXT_AUTO_BR', true);				// automatically add <br> elements for newlines
@define('TEXT_USE_WOFF_FONTS', true);		// (experimental) offer woff webfonts (supported by Firefox 3.6+, Chrome 5.0+, Internet Explorer 9)
@define('VIDEO_ENCODING', true);			// re-encode every uploaded video into a web-optimized, resource-capped 720p variant + poster image (needs ffmpeg installed)
@define('FFMPEG_BINARY', 'ffmpeg');			// path to the ffmpeg binary
@define('VIDEO_ENCODE_CRF', 24);			// x264 quality for the encoded variant (lower is higher quality/larger file)
@define('VIDEO_ENCODE_AUDIO_BITRATE', '64k');	// audio bitrate for the encoded variant
@define('VIDEO_MAX_HEIGHT', 720);			// cap on the short side of the frame (landscape: height, portrait: width) - never upscales a smaller original
@define('VIDEO_MAX_DURATION', 60);			// only the first n seconds of an upload are encoded/served, regardless of how long the original is
@define('VIDEO_DISPLAY_MAX_WIDTH', 512);		// cap the on-canvas size of a newly-encoded video to at most this many pixels wide (0 to disable) - only affects initial display size, not the encoded resolution (VIDEO_MAX_HEIGHT) or file
@define('VIDEO_DISPLAY_MAX_HEIGHT', 512);		// same as above, for height
@define('VIDEO_POSTER_TIME', 1);			// second offset into the video to grab the poster frame from
@define('VIDEO_ENCODE_TIMEOUT', 60*60*2);	// give up waiting for a background encode after n seconds and fall back to the original upload
@define('VIDEO_START_ON_CLICK', true);		// start video on click when autoplay is off
@define('VIEW_NEEDS_AUTH', false);			// viewing pages requires authentication

/**
 * use this function to determine if we should serve HTTPS URLs
 *
 * @return bool
 */
function is_base_url_secure()
{
	if (!empty($_SERVER['HTTPS'])) {
		return true;
	}

	// A front-end server or load balancer is transferring us a request to serve HTTPS to the client.
	if (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https') {
		return true;
	}

	return false;
}

/**
 *	compute the current request's own base url (scheme+host+port+path),
 *	always derived from the request itself regardless of what BASE_URL is
 *	configured to
 *
 *	used where code specifically needs to know the domain the visitor is
 *	actually on right now (e.g. validating the Referer header against XSRF -
 *	see controller.inc.php's invoke_controller()) - base_url() can return a
 *	fixed, different domain than the current request when BASE_URL is
 *	explicitly configured (e.g. a custom domain pointed at this install)
 *
 *	@return string
 */
function request_base_url()
{
	// HTTP_HOST already includes a non-standard port per RFC 7230 - strip
	// it first so it isn't appended twice below (pre-existing bug: e.g.
	// localhost:8931 becoming localhost:8931:8931 whenever this branch
	// actually ran on a non-standard port)
	$host = preg_replace('/:\d+$/', '', $_SERVER['HTTP_HOST']);
	if (!is_base_url_secure()) {
		$ret = 'http://'.$host;
		if ($_SERVER['SERVER_PORT'] != '80') {
			$ret .= ':'.$_SERVER['SERVER_PORT'];
		}
	} else {
		$ret = 'https://'.$host;
		if ($_SERVER['SERVER_PORT'] != '443' && $_SERVER['SERVER_PORT'] != '80') {
			$ret .= ':'.$_SERVER['SERVER_PORT'];
		}
	}
	$ret .= dirname($_SERVER['PHP_SELF']);
	// make sure we have a trailing slash at the end
	if (substr($ret, -1) != '/') {
		$ret .= '/';
	}
	return $ret;
}

/**
 *	use this function to get the site's base url
 *
 *	@return string base url (not html-encoded)
 */
function base_url()
{
	global $base_url_cached;

	$temp = BASE_URL;
	if (!empty($temp)) {
		return $temp;
	} elseif (!isset($base_url_cached)) {
		$base_url_cached = request_base_url();
	}

	return $base_url_cached;
}
