#!/bin/sh
# Regenerate sites.js — the parity page -> the live site it was copied from.
#
# Run this whenever pages are copied into the parity content tree (after
# tools/parity-copy.sh): the map is only as current as the manifest it is
# built from, and a page missing from it simply shows no host in the stage.
#
#   tools/parity-stage/make-sites.sh
#
# Source is tools/parity-sample.tsv (site<TAB>page<TAB>target<TAB>note); the
# site column IS the account name, so the live address is <site>.hotglue.me.
set -e
DIR="$(cd "$(dirname "$0")" && pwd)"
MANIFEST="$DIR/../parity-sample.tsv"
[ -f "$MANIFEST" ] || { echo "no manifest at $MANIFEST" >&2; exit 1; }

{
	cat <<'HEADER'
/* The live site each parity page was copied from: page name -> account, so the
 * stage can say which site it is A/B-ing (<account>.hotglue.me).
 *
 * GENERATED by tools/parity-stage/make-sites.sh from tools/parity-sample.tsv —
 * edit that manifest and re-run it, never this file. The site is NOT derivable
 * from the page name, which is only <site>-<page> by convention: splitting
 * yang-haiscollectinggg-artist at the first dash gives "yang", which is nobody.
 */
window.SITES = {
HEADER
	sed -e '/^#/d' -e '/^[[:space:]]*$/d' "$MANIFEST" |
		awk -F'\t' 'NF >= 3 {
			gsub(/\\/, "\\\\", $3); gsub(/"/, "\\\"", $3);
			gsub(/\\/, "\\\\", $1); gsub(/"/, "\\\"", $1);
			printf "\t%s: %s,\n", "\"" $3 "\"", "\"" $1 "\""	# trailing comma: legal, and keeps every line identical
		}'
	echo "};"
} > "$DIR/sites.js"

printf '%s entries -> %s\n' \
	"$(sed -e '/^#/d' -e '/^[[:space:]]*$/d' "$MANIFEST" | wc -l)" "$DIR/sites.js"
